/** Side-effect imports — register RTK Query endpoints with the base API slice. */
import '@/redux/features/navbar/navbar.api'
import './aboutMeApi'
import './additionalServicesApi'
import './announcement-api'
import './bbbAccreditationApi'
import './blogApi'
import './bookingApi'
import './breakfast-api'
import './calendarApi'
import './certifications-licensing-api'
import './clientsApi'
import './dcpApi'
import './dinner-api'
import './dynamicSectionApi'
import './events-api'
import './faqApi'
import './galleryApi'
import './home-solar-api'
import './insurance-license-api'
import './inventory-api'
import './join-my-team-api'
import './licensing-api'
import './lunch-api'
import './media-press-api'
import './meetOurTeamApi'
import './menuApi'
import './missionStatementApi'
import './myCardApi'
import './postApi'
import './profileAiDataApi'
import './profileSettingsApi'
import './property-listing-api'
import './publicCardsApi'
import './resiliency-products-api'
import './resume-api'
import './reviewsApi'
import './sales-person-api'
import './see-products-api'
import './servicesApi'
import './video-links-api'
import './videoExplainerApi'
import './videosApi'
import './why-choose-us-api'
import './work-experience-api'

export { DEFAULT_PROFILE_SLUG } from '@/lib/constants/profile'
export { useProfile } from '@/redux/features/myCard'
export { useGetNavBarLinksQuery, useLazyGetNavBarLinksQuery } from '@/redux/features/navbar/navbar.api'
export { useGetAboutMeQuery, useLazyGetAboutMeQuery } from './aboutMeApi'
export { useGetAdditionalServicesQuery, useLazyGetAdditionalServicesQuery } from './additionalServicesApi'
export { useGetAnnouncementQuery, useLazyGetAnnouncementQuery } from './announcement-api'
export { useGetBbbAccreditationQuery, useLazyGetBbbAccreditationQuery } from './bbbAccreditationApi'
export { useGetBlogQuery, useLazyGetBlogQuery } from './blogApi'
export { useGetBookingQuery, useLazyGetBookingQuery } from './bookingApi'
export { useGetBreakfastQuery, useLazyGetBreakfastQuery } from './breakfast-api'
export { useGetCalendarQuery, useLazyGetCalendarQuery } from './calendarApi'
export {
  useGetCertificationsLicensingQuery,
  useLazyGetCertificationsLicensingQuery,
} from './certifications-licensing-api'
export { useGetClientsQuery, useLazyGetClientsQuery } from './clientsApi'
export { useGetDcpQuery, useLazyGetDcpQuery } from './dcpApi'
export { useGetDinnerQuery, useLazyGetDinnerQuery } from './dinner-api'
export { useGetDynamicSectionQuery, useLazyGetDynamicSectionQuery } from './dynamicSectionApi'
export { useGetEventsQuery, useLazyGetEventsQuery } from './events-api'
export { useGetFaqQuery, useLazyGetFaqQuery } from './faqApi'
export { useGetGalleryQuery, useLazyGetGalleryQuery } from './galleryApi'
export { useGetHomeSolarQuery, useLazyGetHomeSolarQuery } from './home-solar-api'
export { useGetInsuranceLicenseQuery, useLazyGetInsuranceLicenseQuery } from './insurance-license-api'
export { useGetInventoryQuery, useLazyGetInventoryQuery } from './inventory-api'
export { useGetJoinMyTeamQuery, useLazyGetJoinMyTeamQuery } from './join-my-team-api'
export { useGetLicensingQuery, useLazyGetLicensingQuery } from './licensing-api'
export { useGetLunchQuery, useLazyGetLunchQuery } from './lunch-api'
export { useGetMediaPressQuery, useLazyGetMediaPressQuery } from './media-press-api'
export { useGetMeetOurTeamQuery, useLazyGetMeetOurTeamQuery } from './meetOurTeamApi'
export { useGetMenuQuery, useLazyGetMenuQuery } from './menuApi'
export { useGetMissionStatementQuery, useLazyGetMissionStatementQuery } from './missionStatementApi'
export { useGetMyCardBySlugQuery, useLazyGetMyCardBySlugQuery } from './myCardApi'
export { useGetPostsQuery, useLazyGetPostsQuery } from './postApi'
export { useGetProfileAiDataQuery, useLazyGetProfileAiDataQuery } from './profileAiDataApi'
export { useGetProfileSettingsQuery, useLazyGetProfileSettingsQuery } from './profileSettingsApi'
export { useGetPropertyListingQuery, useLazyGetPropertyListingQuery } from './property-listing-api'
export { useGetPublicCardsQuery, useLazyGetPublicCardsQuery } from './publicCardsApi'
export { useGetResiliencyProductsQuery, useLazyGetResiliencyProductsQuery } from './resiliency-products-api'
export { useGetResumeQuery, useLazyGetResumeQuery } from './resume-api'
export { useGetReviewsQuery, useLazyGetReviewsQuery } from './reviewsApi'
export { useGetSalesPersonQuery, useLazyGetSalesPersonQuery } from './sales-person-api'
export { useGetSeeProductsQuery, useLazyGetSeeProductsQuery } from './see-products-api'
export { useGetServicesQuery, useLazyGetServicesQuery } from './servicesApi'
export { useGetVideoLinksQuery, useLazyGetVideoLinksQuery } from './video-links-api'
export { useGetVideoExplainerQuery, useLazyGetVideoExplainerQuery } from './videoExplainerApi'
export { useGetVideosQuery, useLazyGetVideosQuery } from './videosApi'
export { useGetWhyChooseUsQuery, useLazyGetWhyChooseUsQuery } from './why-choose-us-api'
export { useGetWorkExperienceQuery, useLazyGetWorkExperienceQuery } from './work-experience-api'
